import React, { useState } from "react";
import {
  Box,
  Typography,
  TextField,
  Checkbox,
  FormControlLabel,
  Switch,
  Button,
  Container,
  Paper,
  Stack,
  FormGroup,
  MenuItem,
  Snackbar,
  Alert,
} from "@mui/material";
import StudentHeader from "../../components/StudentHeader";
import { fetchAuthSession } from "aws-amplify/auth";

const CreateCase: React.FC = () => {
  const [isFederal, setIsFederal] = useState(false);
  const [isProvincial, setIsProvincial] = useState(false);
  const [province, setProvince] = useState<string>("");
  const [statuteApplicable, setStatuteApplicable] = useState(false);
  const [broadLaw, setBroadLaw] = useState<string>("");
  const [statuteDetails, setStatuteDetails] = useState<string>("");
  const [overview, setOverview] = useState<string>("");
  const [submitting, setSubmitting] = useState<boolean>(false);

  // Snackbar state
  const [snackbarOpen, setSnackbarOpen] = useState<boolean>(false);
  const [snackbarMessage, setSnackbarMessage] = useState<string>("");
  const [snackbarSeverity, setSnackbarSeverity] = useState<'success'|'error'|'info'|'warning'>('info');

  const showSnackbar = (message: string, severity: 'success'|'error'|'info'|'warning' = 'info') => {
    setSnackbarMessage(message);
    setSnackbarSeverity(severity);
    setSnackbarOpen(true);
  };


  const broadLawOptions = [
    "Criminal Law",
    "Civil Law",
    "Family Law",
    "Business Law",
    "Environmental Law",
    "Health Law",
    "Immigration Law",
    "Labour Law",
    "Personal Injury Law",
    "Tax Law",
    "Intellectual Property Law",
    "Other",
  ];

  const canadianProvinces = [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Northwest Territories",
    "Nova Scotia",
    "Nunavut",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Yukon",
  ];

  const inputStyles = {
    transition: "all 0.3s ease",
    input: {
      WebkitBoxShadow: "0 0 0 1000px var(--background) inset",
      WebkitTextFillColor: "var(--text)",
    },
    "& .MuiOutlinedInput-notchedOutline": {
      borderColor: "var(--border)",
    },
    "&:hover .MuiOutlinedInput-notchedOutline": {
      borderColor: "var(--primary)",
    },
    "& .MuiInputBase-root": {
      backgroundColor: "var(--background)",
      color: "var(--text)",
    },
    "& .MuiInputLabel-root": {
      color: "var(--text)",
    },
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitting(true);
    try {
      const session = await fetchAuthSession();
      const token = session.tokens?.idToken?.toString() || null;
      const userId = session.tokens?.idToken?.payload?.sub as string;
      
      if (!token || !userId) throw new Error('No auth token or user ID available');

      // Step 1: Call /student/new_case to generate case with LLM-generated title
      const jurisdictionArray: string[] = [];
      if (isFederal) jurisdictionArray.push('Federal');
      if (isProvincial) jurisdictionArray.push('Provincial');
      
      const newCasePayload = {
        case_title: "",  // Empty - will be generated by LLM
        case_type: broadLaw,
        jurisdiction: jurisdictionArray.length > 0 ? jurisdictionArray : ['Unknown'],
        case_description: overview,
        province: province || "",
        statute: statuteApplicable ? statuteDetails : "",
      };

      const newCaseResp = await fetch(
        `${import.meta.env.VITE_API_ENDPOINT}/student/new_case?user_id=${userId}`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: token,
          },
          body: JSON.stringify(newCasePayload),
        }
      );

      if (!newCaseResp.ok) {
        const text = await newCaseResp.text();
        throw new Error(`Failed to generate case: ${newCaseResp.status} ${text}`);
      }

      const newCaseData = await newCaseResp.json();
      console.log('case generation response', newCaseData);

      // Step 2: Call /student/edit_case to save the generated case to the database
      const editCasePayload = {
        case_title: newCaseData.case_title || "Untitled Case",
        case_type: broadLaw,
        case_description: overview,
        status: "in_progress",
        jurisdiction: jurisdictionArray.length > 0 ? jurisdictionArray : ['Unknown'],
        province: province || "",
        statute: statuteApplicable ? statuteDetails : "",
      };

      const editCaseResp = await fetch(
        `${import.meta.env.VITE_API_ENDPOINT}/student/edit_case?case_id=${newCaseData.case_id}`,
        {
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
            Authorization: token,
          },
          body: JSON.stringify(editCasePayload),
        }
      );

      if (!editCaseResp.ok) {
        const text = await editCaseResp.text();
        throw new Error(`Failed to save case: ${editCaseResp.status} ${text}`);
      }

      const editCaseData = await editCaseResp.json();
      console.log('case save response', editCaseData);

      showSnackbar(`Case created successfully: ${newCaseData.case_title}`, 'success');

      // reset form
      setIsFederal(false);
      setIsProvincial(false);
      setProvince("");
      setStatuteApplicable(false);
      setBroadLaw("");
      setStatuteDetails("");
      setOverview("");
    } catch (err) {
      console.error('Failed to submit case', err);
      const msg = err instanceof Error ? err.message : 'Failed to submit case';
      showSnackbar(msg, 'error');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <Box
      sx={{
        backgroundColor: "var(--background)",
        minHeight: "100vh",
        color: "var(--text)",
        display: "flex",
        flexDirection: "column",
      }}
    >
      <StudentHeader />
      
      <Container
        maxWidth="xl"
        sx={{
          mt: 4,
          mb: 4,
          flexGrow: 1,
          display: "flex",
          justifyContent: "center",
          alignItems: "flex-start",
        }}
      >
        <Paper
          elevation={0}
          sx={{
            width: "100%",
            maxWidth: "800px",
            backgroundColor: "var(--background)",
            border: "1px solid var(--border)",
            p: 4,
            borderRadius: 2,
            display:"flex",
            flexDirection: "column",
            alignItems: "flex-start",
          }}
        >
          <Typography variant="h5" sx={{ mb: 3, color: "var(--text)" }}>
            Create a Case
          </Typography>

          <form onSubmit={handleSubmit} style={{ width: '100%' }}>
            <Stack spacing={3} width="100%">
              {/* Broad Area of Law */}
              <TextField
                select
                fullWidth
                label="Broad Area of Law"
                value={broadLaw}
                onChange={(e) => setBroadLaw(e.target.value as string)}
                variant="outlined"
                sx={{ ...inputStyles, textAlign: "left" }}
              >
                {broadLawOptions.map((opt) => (
                  <MenuItem value={opt} key={opt} sx={{ textAlign: 'left' }}>
                    {opt}
                  </MenuItem>
                ))}
              </TextField>

              {/* Jurisdiction */}
              <Box >
                <Typography
                  variant="subtitle1"
                  sx={{mb: 1, color: "var(--text)", textAlign: "left" }}
                >
                  Jurisdiction
                </Typography>
                <FormGroup>
                  <FormControlLabel
                    control={
                      <Checkbox
                        checked={isFederal}
                        onChange={(e) => setIsFederal(e.target.checked)}
                        sx={{
                          color: "var(--text-secondary)",
                          "&.Mui-checked": { color: "var(--primary)" },
                        }}
                      />
                    }
                    label={
                      <Typography sx={{ color: "var(--text-secondary)" }}>
                        Federal
                      </Typography>
                    }
                  />
                  <FormControlLabel
                    control={
                      <Checkbox
                        checked={isProvincial}
                        onChange={(e) => {
                          const checked = e.target.checked;
                          setIsProvincial(checked);
                          if (!checked) setProvince("");
                        }}
                        sx={{
                          color: "var(--text-secondary)",
                          "&.Mui-checked": { color: "var(--primary)" },
                        }}
                      />
                    }
                    label={
                      <Typography sx={{ color: "var(--text-secondary)" }}>
                        Provincial
                      </Typography>
                    }
                  />
                </FormGroup>

                {isProvincial && (
                  <TextField
                    select
                    fullWidth
                    label="Province / Territory"
                    value={province}
                    onChange={(e) => setProvince(e.target.value as string)}
                    variant="outlined"
                    sx={{ ...inputStyles, textAlign: "left" }}
                  >
                    {canadianProvinces.map((p) => (
                      <MenuItem value={p} key={p} sx={{ textAlign: 'left' }}>
                        {p}
                      </MenuItem>
                    ))}
                  </TextField>
                )}
              </Box>

              {/* Statute Applicable? */}
              <Stack direction="row" alignItems="center" spacing={1}>
                <Typography
                  variant="subtitle1"
                  sx={{color: "var(--text)" }}
                >
                  Statute Applicable?
                </Typography>
                <Switch
                  checked={statuteApplicable}
                  onChange={(e) => setStatuteApplicable(e.target.checked)}
                  sx={{
                    "& .MuiSwitch-switchBase.Mui-checked": {
                      color: "#90caf9",
                      "& + .MuiSwitch-track": {
                        backgroundColor: "#64b5f6",
                      },
                    },
                  }}
                />
              </Stack>

              {/* Statute Details */}
              {statuteApplicable && (
                <TextField
                  fullWidth
                  label="Statute Details"
                  variant="outlined"
                  sx={{...inputStyles}}
                  value={statuteDetails}
                  onChange={(e) => setStatuteDetails(e.target.value)}
                />
              )}

              {/* Overview */}
              <TextField
                fullWidth
                multiline
                rows={6}
                label="Provide an overview of the details of the case"
                variant="outlined"
                sx={inputStyles}
                value={overview}
                onChange={(e) => setOverview(e.target.value)}
              />

              {/* Start Chat Button */}
              <Button
                type="submit"
                variant="contained"
                fullWidth
                disabled={submitting}
                sx={{
                  backgroundColor: "#76b9f0",
                  color: "var(--text)",
                  textTransform: "none",
                  fontSize: "1rem",
                  py: 1.5,
                  "&:hover": {
                    backgroundColor: "#5a9bd0",
                  },
                }}
              >
                {submitting ? 'Creating...' : 'START CHAT'}
              </Button>
            </Stack>
          </form>
        </Paper>
      </Container>

      <Snackbar open={snackbarOpen} autoHideDuration={4000} onClose={() => setSnackbarOpen(false)}>
        <Alert onClose={() => setSnackbarOpen(false)} severity={snackbarSeverity} sx={{ width: '100%' }}>
          {snackbarMessage}
        </Alert>
      </Snackbar>
    </Box>
  );
};

export default CreateCase;
